PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX madridonc: <http://madridalfresco.es/lcc/ontology/locales#>
PREFIX madridrec: <http://madridalfresco.es/lcc/resource/>

#Number of terraces with more or 20 chairs.
SELECT (count(?Terraza) as ?o) 
WHERE { 
    ?Terraza a madridonc:Terraza;
        madridonc:sillas ?sillas;
    FILTER(?sillas>=20).
}

#Result: (rdflib.term.Literal('5127', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer')),)

#The first 5 districts with no avenues
SELECT (?Distrito as ?o)
WHERE {
  ?Distrito rdf:type madridonc:Distrito;
	          madridonc:tipoVia ?via;
  FILTER(?via!="AVENIDA").
} LIMIT 5

#Result:	(rdflib.term.URIRef('http://madridalfresco.es/lcc/resource/Distrito/SBC'),)
#(rdflib.term.URIRef('http://madridalfresco.es/lcc/resource/Distrito/SBC'),)
#(rdflib.term.URIRef('http://madridalfresco.es/lcc/resource/Distrito/SBC'),)
#(rdflib.term.URIRef('http://madridalfresco.es/lcc/resource/Distrito/SBC'),)
#(rdflib.term.URIRef('http://madridalfresco.es/lcc/resource/Distrito/S'),)

#Name of the restaurants in Salamanca district
SELECT DISTINCT ?obj ?ndir WHERE {
  ?loc rdf:type madridonc:Local ;
       madridonc:rotulo ?obj ;
       madridonc:perteneceADistrito ?dist .
  ?dist madridonc:nombreDistrito ?ndir
  FILTER(?ndir = "SALAMANCA")
}

#Result
#(rdflib.term.Literal('HONTANARES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR MARISQUERIA LUIS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SAGAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('WAGABOO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('THE JAMES JOYCE IRISH PUB'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HOTEL ABBA MADRID'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL NUEVO RINCON DE JAEN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VIENA CAPELLANES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA PARISIENA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL ARBOL Y LA TOSTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA PICOTERA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA NIÑA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JARRITUS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR CALVIN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CERVEZERIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL BARRIL                                         '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR SIDNEY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LIZARRAN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('FRESNO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL RINCON DE DALI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA JARRA Y LA PIPA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MUESTRA CORPORATIVA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MANDARIZ CAFE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MAMA NO LO SABE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MEMPHIS COCKTAIL BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERA JARA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA NUMAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA EL TREBOL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JACARANDA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA CERVECERIA BIARRITZ'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFE Y TE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RODILLA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA GOMEZ'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA EL RUEDO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ANELL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GIANGROSSI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HOTEL ADLER'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VIPS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('101 MONTADITOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TARBENA DE ORTEGA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL PESCADOR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA DEL OLIVO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MONTE CASTELA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CERVECERIA MANCILES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('OSAKA RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JOSE LUIS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MAS Q MENOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SANXENXO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PINCHOS UDABERRI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BULEVAR 54'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('REGATES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA BARRA DE LA BIENTIRADA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL PARAGUAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA RESTAURANTE GONGORA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('WINGS4U'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR RESTAURANTE LEON                              '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFE SILMA BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA DOMINGO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL PALADAR                               '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PASACALLES BAR RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE CHINO LI MING                         '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MAKKILA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE CERVECERIA CASA LEANDRO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TRAVIESA                                           '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MARTINICA GASTROBAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VILLALOBILLOS CERVECERIA RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DE PARTIDA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA DEL PUERTO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HOTEL BLESS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA DOMA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('AZIZ ISTAMBUL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA J.M.'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DUENDE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR CAFETERIA ELISABETH'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL RINCON DE JAEN II'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA VALOR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE THONG'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TANTEO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA LA CONSERVA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SOBRE VINO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CASSETA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MILFORD'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('NO SOLICITADO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("O'CLOCK"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE CRUZ CAFE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TABERNA DEL PINTOR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA LLAVE DE ORO CAFETERIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TAGLIATELLA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA 100 MONTADITOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LE PETIT PRINCIPE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PANELA & CO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL CHORRON'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA DAVID'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LOS LARES DEL PARQUE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('STARBUCKS COFFEE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('AL CAPRICHO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('COPENHAGEN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("TOMMY MEL'S"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA VERGARA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TRESS PUB                                         '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DIEZ HOYOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PANS & COMPANY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE MARTINETE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MUESTRAS SOBRE DINTELES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE EL MIRADOR CAFETERIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CLAVE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA LA SUREÑA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ENSALADAS Y MAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BIOTZA  BAR-RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BECQUER 6 FOOD & DRINKS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA PERCHA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('KING DONER KEBAD'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR VALLADARES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA PANERIE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL GRAN BARRIL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA COLONIAL  DE GOYA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DEFILE CAFE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA SOTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MARAVILLAS III MUJIGATO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PIMIENTO VERDE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BENDITA LOCURA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL HORNO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('OKAFU TABERNA GALLEGA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA DIVINA DE GOYA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MESON RESTAURANTE EL HORREO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA EL COCODRILO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SENY                                              '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL ASADOR DE ARANDA                               '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SOÑA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EZARO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CASA DEL ABUELO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA BOIGA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR RESTAURANTE JESUS                             '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TELEPIZZA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VERGARA 97 '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GOYESCA II'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LE CAFE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CASA DE LA CERVEZA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GREEN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JUICY AVENUE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BOTILLO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LE PAIN QUOTIDIEN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ODDS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SILVELA 77'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TASCA LA FARMACIA                                 '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ESBARDOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("TABEL'LA"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VE-GA BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MANOLO BAKES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA PACO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MALLORCA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MILOS RESTAURANTE GRIEGO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TERRUCA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA CANDILEJAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('FRANK AND FURT'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MUESTRA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('KEBAB PALACE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LATERAL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("FRANQUICIA O'DONNELL 17, S.L."), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL MESTIZO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASTIZO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VOLAPIE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA COLINA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SEBAGO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TUERTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE ALBORA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL GORDO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA PITTU'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SHUZOS BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DSTILLS URBAN DISTILLERY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE LOS PALOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA SALA MANCA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("RESTAURANTE CAFETERIA TINO'S"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BESTIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DO EAT FOOD'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA ANTIGUA CHURRERIA                                   '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL CUENTO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ALEXANDER II'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MOLIERE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SUGARCANE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR HERMANOS ORDAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DERMACOM MARKETING S.L.'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BARRA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HOYO 19'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SHUKRAN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFE SAIGON'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SUNGLASS HUT'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TIGER'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SOTANILLO                                         '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA TAURINA EL TABLON'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA MUCCA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DORINDA PERFUMERIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HOTEL MELIA LOS GALGOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA MAQUINA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BISCOTTO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ESPLORE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VACA PICADA 3'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('FLORES DE ALCACHOFA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VINOTINTO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR RAFAELA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DON CARMELO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BANESTO AGENTE FINANCIERO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('FABORIT'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JOHNSON'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MESON CINCO JOTAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RICOS TACOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DINGO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JOSELITOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CARLOTA DESAYUNOS Y COMIDAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA GUSA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA COCHERA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('WAHINE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('20 A LA CATA                                  '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA ESTEBAN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA RETAURANTE GALATEA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TERRA CELTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JUANITA ME MATA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LAVINIA ESPAÑA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA CESAR LAS VENTAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA SOÑA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE MARCONI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA DEGUSTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MANA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA LEVANTERA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SIN ROTULO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR-RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR CHOCALA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR GOYA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TAIGA MADRID'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VINOPREMIER'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA ENCANTADA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VALNAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ARBOREA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PUB DREAMS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LUXURY SUITES MADRID'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BURGER KING'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HACHES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GRANIER'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HONEST GREENS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('KLAATU                                            '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESET'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('VIDING ALCANTARA C.D.M.'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BEST'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MAGASAND'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GASSET 75'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PIU BELLA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DELINAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TIEMPOS MAGICOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR MARTIN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR LOS TORREZNOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PINO BER CERVECERIA RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GUILTY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BURGUER KING'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAPPUCCHINO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('POP TAPAS Y COPAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('NICE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ISTAMBUL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HELADOS SIENNA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL TXOKO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PINCHOS ELCANO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA JL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HOSPES PUERTA DE ALCALA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RAMSES LIFE & FOOD'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SHUKRAN CITY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR MENENDEZ'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TGB'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL RINCON DE JAEN IV'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SIN NOTIFICAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TERCIOS DE FLANDES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA MANON'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PERFILES CAFE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SUSHI SHOP'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA EL QUITE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("MCDONALD'S"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE INDIAN CUISINE TANDOORI STATION'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR ESQUERDO 16'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ARROCERIA EL SEÑORET'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAKERS & COFFEE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('COTICO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("O'DONNELL 11"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LOS GALLOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA CATALINA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TRES DIAMANTES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('212 BISTRO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('STARBUCKS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('QUINTA LA CANDELA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BERTIZ'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CONACHE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MORAO TAPAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('POLVORA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ICON EMBASSY BY PETIT PALACE                           '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MOLACUATRO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('FIVE GUYS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL HORREO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RELIGION'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA LOS TIMBALES'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA GATO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA SALUS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA CRIMI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE LA PLAZA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ANIMARI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('DIFERENT'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SANTAGLORIA CAFFEE & BAKERY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CONOCO EL BABERO S.L.'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('POR DETERMINAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LARA GRILL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BUMP GREEN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFE & TE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA EL BARRIO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PANARIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL 41'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL 27'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CRISTINA ORIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CARBON NEGRO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA LA PLANCHA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BARRA AGUSTIN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BAR LUSA                                          '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL PARADOR DEL JAMON'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ARACENA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ALIMENTACION'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL CALLEJON DEL PARQUE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL CANO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('BRINDIS BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE LA PALOMA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('NACIONSUSHI'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('JORDAN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA MANDUCA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA PETO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LAS CAÑAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA MONTESA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA PULPERIA DE MILA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE CAZORLA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE ALONSO HERMANOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MALA FEMMENA- RESTARUANTE ITALIANO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MOCCA CAFE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CAFETERIA CERVECERIA CRISER'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CERVECERIA LA TONA DESDE 1969'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('HERITAGE HOTEL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA GARRIGA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA AL NATURAL'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CASA JULIAN                                       '), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TUK TUK'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA EL RINCON DE PARDIÑAS RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL RINCON DE JAEN'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SALA DE FIESTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RONDA 14'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA CHARLOTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal("DOMINO'S PIZZA"), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL BARRIL DE RECOLETOS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CARPE DIEM'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA BODEGA DEL OSO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA EL TORITO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('V. MENOR EMBUTIDOS CON BARRA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('PINTXOTERAPIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MINI SUSHI BAR'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA FLOR DE GALICIA RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('FONTY'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA BARRA DE LA BIEN TIRADA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MORE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('ARUGULA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LAS BECEAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MAISON KAYSER PARIS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('COCINA DE MERCADO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('TABERNA LAS BOTAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('GASTROBAR AROMAS'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('RESTAURANTE GERARDO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CILINDRO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SARGO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TIENTA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('CATALPA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA PARILLA DE SALAMANCA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('SANTAGLORIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA TASQUERIA'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('EL GOURMET DE OLMEDO'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LE COQ'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('MONTEAGUDO CERVECERIA RESTAURANTE'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('WAY CUP'), rdflib.term.Literal('SALAMANCA'))
#(rdflib.term.Literal('LA BODEGA DE CASANOVA'), rdflib.term.Literal('SALAMANCA'))

#Name of the restaurants and the street names
SELECT DISTINCT ?obj ?ndir WHERE {
  ?loc rdf:type madridonc:Local ;
       madridonc:rotulo ?obj ;
       madridonc:perteneceADistrito ?dist .
  ?dist madridonc:nombreCalle ?ndir.
} LIMIT 4

#Result: (rdflib.term.Literal('SR'), rdflib.term.Literal('SOFIA'))
#(rdflib.term.Literal('SR'), rdflib.term.Literal('MIERES'))
#(rdflib.term.Literal('SR'), rdflib.term.Literal('OCCIDENTE'))
#(rdflib.term.Literal('SR'), rdflib.term.Literal('VALDECANILLAS'))