# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oW2SAc6jJST0mFjVmBbyBVeo5IHuPVIh

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

# Solo para visualizar los datos
for s,p,o in g:
  print(s,p,o)

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
# Visualize the results
from rdflib.plugins.sparql import prepareQuery

q1 = prepareQuery('''
  SELECT ?Subject WHERE {
    ?Subject rdfs:subClassOf ns:LivingThing
  }
  ''',
  initNs = { "vcard": VCARD, "ns": ns}
)

for r in g.query(q1):
 print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
# Visualize the results
q2 = prepareQuery('''
  SELECT ?Subject
  WHERE {
    {
    ?Subject rdf:type ns:Person
    } UNION {
     ?Subject1 rdfs:subClassOf ns:Person.
     ?Subject rdf:type ?Subject1
    }
  }
  ''',
  initNs = { "vcard": VCARD, "ns": ns}
)

for r in g.query(q2):
 print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
# Visualize the results
q3 = prepareQuery('''
  SELECT ?Subject ?property ?value WHERE {
      ?Subject rdf:type ?o.
      FILTER (?o = ns:Person || ?o = ns:Animal).
      ?Subject ?property ?value
  }
  ''',
  initNs = { "vcard": VCARD, "ns": ns}
)

for r in g.query(q3):
 print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
# Visualize the results
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")

knowsRockySmith = g.triples((None, FOAF.knows, ns.RockySmith))

for s,p,o in knowsRockySmith:
  givenName = g.value(subject=s, predicate=VCARD.Given, object=None)
  print(givenName)
  #Profesor, no entiendo por qué me imprime None en vez de imprimir los Given Names

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
# Visualize the results
from collections import defaultdict
counter = defaultdict(int)

for s, p, o in g.triples((None, FOAF.knows, None)):
  counter[s] += 1
for entity, count in counter.items():
  if count >=2:
    print (entity)