# -*- coding: utf-8 -*-
"""SPARQLqueries-with-links

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10X3MBRUROpm1n5j44dwucRfsz2N_qlwf
"""

!pip install rdflib

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS

g = Graph()
g.parse("RDF_healthCenters-with-links.ttl", format="ttl")

foaf = Namespace("http://xmlns.com/foaf/0.1/")
RDF = ("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
vcard = ("http://www.w3.org/2001/vcard-rdf/3.0#")
vocab = Namespace ("http://healthcentersmadrid.es/locations/ontology/ont#")

from rdflib.plugins.sparql import prepareQuery

#List thre name of 20 districts and their links.
q1 = prepareQuery('''
  SELECT ?entity ?name ?link
  WHERE {
    ?entity rdf:type vocab:HealthCenter.
    ?entity vocab:name ?name.
    ?entity vocab:Location ?Location.
    ?Location vocab:Address ?Address.
    ?Address vocab:district_wikidata ?link.
  }
  LIMIT 20
  ''',
  initNs = { "rdf": RDF, "vocab":vocab}
)

# Visualize the results
for s in g.query(q1):
  print(s.name, s.link)

from rdflib.plugins.sparql import prepareQuery
#List 20 entities and the link to the neighbourhood they are part of.
q2 = prepareQuery('''
  SELECT ?entity ?name ?link
  WHERE {
    ?entity rdf:type vocab:HealthCenter.
    ?entity vocab:name ?name.
    ?entity vocab:Location ?Location.
    ?Location vocab:Address ?Address.
    ?Address vocab:neighbourhood_wikidata ?link.
  }
  LIMIT 20
  ''',
  initNs = { "rdf": RDF, "vocab":vocab}
)

# Visualize the results
for s in g.query(q2):
  print(s.entity,s.link)