# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8i4DudaUUfXYvddMYzIR7Bv6OIYl-N8

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS, FOAF
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")
ns = Namespace("http://data.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

for s,p,o in g1.triples((None, RDF.type, ns.Person)):
    missingFields = [VCARD.Given, VCARD.Family, VCARD.EMAIL]
    for s1,p1,o1 in g1.triples((s, None, None)):
          if p1 != RDF.type and p1 in missingFields:
                missingFields.remove(p1)
    # filling the blanks
    for field in missingFields:
        for s2,p2,o2 in g2.triples((s, field, None)):
            g1.add((s, p2, o2))

print(g1.serialize(format="ttl"))