# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFTF2scJqcBgcj4wro14jPbfnBUaFSB4

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://www.example.org#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
ns = Namespace("http://example.org#")
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

janeURI = ns.JaneSmith
g.add((janeURI, RDF.type, ns.Researcher))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmith the email address, fullName, given and family names**"""

from rdflib import XSD
janeURI = ns.JaneSmith

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

g.add((janeURI, VCARD.FN, Literal("Jane Smith", datatype=XSD.string)))
g.add((janeURI, VCARD.email, Literal("janesmith@example.com", datatype=XSD.string)))
g.add((janeURI, VCARD.Given, Literal("Jane", datatype=XSD.string)))
g.add((janeURI, VCARD.Family, Literal("Smith",datatype=XSD.string)))

for s,p,o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

from rdflib import URIRef
johnURI = ns.JohnSmith
workProperty = ns.wroksAt
g.add((ns.UPM, RDF.type, ns.University))
g.add((johnURI, workProperty, ns.UPM))

"""**Task 6.6: Add that John knows Jane using the FOAF vocabulary**"""

from rdflib.namespace import FOAF

g.add((johnURI, FOAF.knows, janeURI))

