# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nC4EvpmNhzUdnYrAaxeYjILd8cLCubAE

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

for s,p,o in g1:
  print(s,p,o)

from rdflib.namespace import RDF, OWL

ns = Namespace("http://data.org#")
vcard = Namespace('http://www.w3.org/2001/vcard-rdf/3.0#')

for s, p, o in g1.triples((None, vcard.FN, None)):
    for ss, pp, oo in g2.triples((None, vcard.FN, o)):
        fn1 = g1.value(s, vcard.familyName)
        fn2 = g2.value(ss, vcard.familyName)
        if fn1 and fn2 and fn1 == fn2:
            g3.add((s, OWL.sameAs, ss))

for s,p,o in g3:
  print(s,p,o)

