# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dahp6kJ0WDxvp8NIIRER9FOYuPg2mJyd

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")
for (s, p, o) in g:
  print(s,p,o)

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
from rdflib.plugins.sparql import prepareQuery

RDFS = Namespace("http://www.w3.org/2000/01/rdf-schema#")

q1 = prepareQuery('''
  SELECT ?Subject WHERE {
    ?Subject rdfs:subClassOf* <http://somewhere#LivingThing>.
  }
  ''',
    initNs = { "rdfs": RDFS}
)

# Visualize the results

for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
q1 = prepareQuery('''
  SELECT ?Subject WHERE {
    ?Subject a ?Class.
    ?Class rdfs:subClassOf* <http://somewhere#Person>.
  }
  ''',
    initNs = { "rdfs": RDFS}
)

# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
q1 = prepareQuery('''
  SELECT ?Subject ?Property ?Value WHERE {
    ?Subject ?Property ?Value.
    {?Subject a <http://somewhere#Person>.}
    UNION
    {?Subject a <http://somewhere#Animal>.}
  }
  ''',
    initNs = { "rdfs": RDFS}
)
# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

from rdflib import FOAF, Namespace
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
# TO DO
q1 = prepareQuery('''
  SELECT ?Subject WHERE {
    ?Subject foaf:knows <http://somewhere#RockySmith>.
  }
  ''',
    initNs = { "foaf": FOAF, "vcard":VCARD}
)
# Visualize the results
for r in g.query(q1):
  print(r)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
q1 = prepareQuery('''
  SELECT distinct ?Subject WHERE {
    ?Subject foaf:knows ?z.
    ?Subject foaf:knows ?y.
    FILTER(?y != ?z)
  }
  ''',
    initNs = { "foaf": FOAF}
)
# Visualize the results
for r in g.query(q1):
  print(r)