# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p0r_78jYUDQtIywwl4qPVa5hvjAvWt0w

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib import OWL
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
for uri1,p1,giv1 in g1.triples((None, VCARD.Given, None)):
  for (uri2,p2,giv2) in g2.triples((None, VCARD.Given, giv1)):
      for uri11,p11,fam1 in g1.triples((uri1, VCARD.Family, None)):
        for (uri21,p21,fam2) in g2.triples((None, VCARD.Family, fam1)):
          resource=(uri1,OWL.sameAs,uri2)
          g3.add(resource)

for (s3,p3,o3) in g3.triples((None,None,None)):
  print(s3,p3,o3)