PREFIX db: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Query: Select all distinct predicates -excluding rdf:type- that are used as properties of subjects of type Politician
SELECT DISTINCT ?predicate_properties
WHERE {
    # 1. Get all subjects of type Politician
    ?subject a db:Politician .
    
    # 2. For each subject of type Politician, retrieve all predicates (and objects -albeit unused)
    ?subject ?predicate_properties ?object_placeholder .
    
    # 3. And exclude rdf:type
    FILTER(?predicate_properties != rdf:type)
}
