# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhPWCy6QQD86Vs8D31MiExUINziMxA-H

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

g.add((ns.University, RDF.type, RDFS.Class))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

print("\n\nTTL:\n")
print(g.serialize(format="ttl"))

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

print("\n\nTTL:\n")
print(g.serialize(format="ttl"))

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

g.add((ns.JaneSmith, RDF.type, ns.Researcher))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

print("\n\nTTL:\n")
print(g.serialize(format="ttl"))

"""**TASK 6.4: Add to the individual JaneSmith the email address, fullName, given and family names**"""

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
#https://www.w3.org/TR/vcard-rdf/
g.add((ns.JaneSmith, vcard.EMAIL, Literal("janesmith@gmail.com")))
g.add((ns.JaneSmith, vcard.FN, Literal("Jane Smith")))
g.add((ns.JaneSmith, vcard.Given, Literal("Jane")))
g.add((ns.JaneSmith, vcard.Family, Literal("Smith")))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

print("\n\nTTL:\n")
print(g.serialize(format="ttl"))

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

g.add((ns.UPM, RDF.type, ns.University))
g.add((ns.JohnSmith, ns.WorksAt, ns.UPM))
# Visualize the results
typeUni = g.triples((ns.UPM, RDF.type, None))
worksAt = g.triples((None, ns.WorksAt, ns.UPM))

for s, p, o in typeUni:
  print(s,p,o)

for s, p, o in worksAt:
  print(s,p,o)

print("\n\nTTL:\n")
print(g.serialize(format="ttl"))

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary**"""

foaf = Namespace("http://xmlns.com/foaf/0.1/")
# Visualize the results
g.add((ns.JohnSmith, foaf.knows, ns.JaneSmith))
knows = g.triples((None, foaf.knows, ns.JaneSmith))

for s, p, o in knows:
  print(s,p,o)

print("\n\nTTL:\n")
print(g.serialize(format="ttl"))

