# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZugLhrJNtflLHjWOblOkKnppeLiRXw4

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import RDF, OWL
from rdflib.plugins.sparql import prepareQuery

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

print("1. Se muestran todos los datos que tiene el grafo 1.")
for s,p,o in g1.triples((None, None, None)):
  print(s,p,o)

print("\n")
print("2. Se muestran todos los datos que tiene el grafo 2.")
for s,p,o in g2.triples((None, None, None)):
  print(s,p,o)

print("\n")
print("3. Se identifican individuos iguales si tienen mimsmo apodo y nombre de familia en rdflib.")
for s,p,o in g1.triples((None, vcard.Given, None)):
    for ss,pp,O_RDONLY in g2.triples((None, vcard.Given, o)):
        if (s, vcard.Family, None) in g1 and (ss, vcard.Family, None) in g2:
            if g1.value(s, vcard.Family) == g2.value(ss, vcard.Family):
                g3.add((s, OWL.sameAs, ss))

for s,p,o in g3.triples((None, None, None)):
  print(f"Indiviudal: {s}; Property: {p}; Object: {o}")

print("\n")
print("4. Se identifican individuos iguales si tienen mimsmo apodo y nombre de familia en SPARQL.")
q1 = prepareQuery('''
  SELECT
    ?Subject ?Given ?Family
  WHERE {
    ?Subject vcard:Given ?Given.
    ?Subject vcard:Family ?Family
  }
  ''',
  initNs = { "vcard": vcard }
)

for i in g1.query(q1):
    for j in g2.query(q1):
        if i[1] == j[1] and i[2] == j[2]:
            g3.add((i[0], OWL.sameAs, j[0]))

for s,p,o in g3.triples((None, None, None)):
  print(f"Indiviudal: {s}; Property: {p}; Object: {o}")