PREFIX nso: <http://madridwastemanagement.org/group01/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


# Qurey 1:  Check all the entities with Wikidata link
SELECT ?entity WHERE {
  ?entity owl:sameAs ?wikidataLink .
  FILTER(STRSTARTS(STR(?wikidataLink), "http://wikidata.org/entity/"))
}


# Query 2: Check all the district with Wikidata link
PREFIX data: <http://madridwastemanagement.org/group01/ontology/data/District/>

SELECT ?district ?wikidataLink WHERE {
  ?district a nso:District .
  ?district owl:sameAs ?wikidataLink .
}


# Query 3: Check all the wasteType with Wikidata link
PREFIX data: <http://madridwastemanagement.org/group01/ontology/data/WasteType/>

SELECT distinct ?wasteType ?wikidataLink WHERE {
  ?s nso:hasResidue ?wasteType .
  ?wasteType owl:sameAs ?wikidataLink .
}



