# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lv2-pNkfm7CwgMKQwy0NXzu33Yv9qkTh

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS

g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery
from rdflib import FOAF

ns = Namespace("http://somewhere#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

print("SPARQL VERSION:")

q1 = prepareQuery('''
  SELECT ?subClasses WHERE {
    ?subClasses rdfs:subClassOf ns:LivingThing.
  }
  ''',
  initNs = {"ns": ns, "rdfs": RDFS}
)

for r in g.query(q1):
  print(r.subClasses)

print("\nRDFLib VERSION:")

for t,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
  print(t)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# SPARQL VERSION
print("SPARQL VERSION:")
q2 = prepareQuery('''
  SELECT ?individuals WHERE {
    ?subclasses rdfs:subClassOf* ns:Person.
    ?individuals a ?subclasses.
  }
''',
  initNs = {"ns": ns, "rdfs": RDFS}
)

for r in g.query(q2):
    print(r.individuals)

# RDFLib VERSION
print("\nRDFLib VERSION:")

for t,p,o in g.triples((None, RDF.type, ns.Person)):
  print(t)

for t,p,o in g.triples((None, RDFS.subClassOf, ns.Person)):
  for a,b,c in g.triples((None, RDF.type, t)):
    print(a)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# SPARQL VERSION
print("SPARQL VERSION:")
q3 = prepareQuery('''
  SELECT ?individual ?property ?value WHERE {
    ?individual a ?class.
    ?individual ?property ?value.
    FILTER (?class = ns:Person || ?class = ns:Animal)
  }
''',
  initNs = {"ns": ns, "rdfs": RDFS}
)

for r in g.query(q3):
    print(f"Individual: {r.individual}, Property: {r.property}, Value: {r.value}")

# RDFLib VERSION
print("\nRDFLib VERSION:")

individuals = set()
properties = set()

for s, o in g.subject_objects(RDF.type):
    if o == ns.Person or o == ns.Animal:
        individuals.add(s)
        for p, v in g.predicate_objects(s):
            properties.add((s, p, v))

for i, p, v in properties:
    print(f"Individual: {i}, Property: {p}, Value: {v}")

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# SPARQL VERSION
print("SPARQL VERSION:")
q4 = prepareQuery('''
  SELECT ?name WHERE {
    ?person <http://xmlns.com/foaf/0.1/knows> <http://somewhere#RockySmith>.
    ?person <http://www.w3.org/2001/vcard-rdf/3.0/FN> ?name.
  }
''')

print(f"Person who knows Rocky:")
for r in g.query(q4):
    print(r.name)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# RDFLib Version
print("\nRDFLib VERSION:")

knowledge_dict = {}

for s, o in g.subject_objects(FOAF.knows):
    if s not in knowledge_dict:
        knowledge_dict[s] = set()
    knowledge_dict[s].add(o)

entities_with_multiple_known = [entity for entity, known in knowledge_dict.items() if len(known) >= 2]

print(f"Entity who knows at least two others:")
for entity in entities_with_multiple_known:
     print(entity)