# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eO3pfxdvlkEe6_XF7BIoDlE3oN72eqGy

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
from rdflib.plugins.sparql import prepareQuery
ns = Namespace("http://somewhere#")
q1 = prepareQuery(
    '''SELECT ?subClass
    WHERE { ?subClass rdfs:subClassOf ns:LivingThing. }''',
    initNs={"rdfs": RDFS, "ns": ns}
)
# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
q2 = prepareQuery(
    '''SELECT ?person ?type
    WHERE {
      ?person rdf:type ?type .
      ?type rdfs:subClassOf* ns:Person .
    }''',
  initNs = {"rdf": RDF, "rdfs": RDFS, "ns": ns}
)
# Visualize the results
for r in g.query(q2):
  print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
q3 = prepareQuery(
    ''' SELECT ?person ?class ?property ?value
    WHERE {
        ?person rdf:type ?class .
        ?person ?property ?value .
        FILTER(?class = ns:Person || ?class = ns:Animal)
    }''',
    initNs={"rdf": RDF, "ns": ns}
)
# Visualize the results
for r in g.query(q3):
 print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
from rdflib import FOAF
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0")
foaf = Namespace("http://xmlns.com/foaf/0.1/")

q4 = prepareQuery(
    '''SELECT DISTINCT ?person
    WHERE {
        ?person foaf:knows ns:RockySmith .
    }''',
    initNs={"rdf": RDF, "rdfs": RDFS, "ns": ns, "foaf":FOAF}
)
# Visualize the results
for r in g.query(q4):
 print(r)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
# Visualize the results
q5 = prepareQuery(
    '''SELECT ?entity
    WHERE {
        ?entity foaf:knows ?otherEntity .
        ?entity foaf:knows ?otherEntity2 .
        FILTER (?otherEntity != ?otherEntity2)
    }
    GROUP BY ?entity''',
    initNs={"foaf": FOAF}
)
# Visualize the results
for r in g.query(q5):
  print(r)