# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_I-mI5QmndzqILg2Qh1D7b-JhkjRORnr

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS, FOAF
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery
from rdflib.namespace import FOAF
ns = Namespace("http://somewhere#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

# TO DO
Query1 = prepareQuery('''

  SELECT ?subClass WHERE {
    ?subClass rdfs:subClassOf ns:LivingThing.
  }
  ''',
  initNs = { "vcard": vcard, "rdfs":RDFS, "ns":ns}
)

# Visualize the results
for r in g.query(Query1):
  print(r.subClass)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
Query2 = prepareQuery('''

  SELECT ?individual WHERE {
    {
      ?individual rdf:type ?subClass.
      ?subClass rdfs:subClassOf ns:Person.
    }
    UNION
    {
      ?individual rdf:type ns:Person.
    }
  }
  ''',
  initNs = { "vcard": vcard, "rdfs":RDFS, "ns":ns}
)


# Visualize the results
for r in g.query(Query2):
  print(r.individual)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
Query3 = prepareQuery('''

  SELECT DISTINCT ?individual ?properties ?value WHERE {
    { #Persons
        {
            ?individual rdf:type ?subClass.
            ?subClass rdfs:subClassOf ns:Person.
            ?individual ?properties ?value
        }
        UNION
        {
            ?individual rdf:type ns:Person.
            ?individual ?properties ?value
        }
    } #Persons
    UNION
    { #ANIMALS
        {
            ?individual rdf:type ?subClass.
            ?subClass rdfs:subClassOf ns:Animal.
            ?individual ?properties ?value
        }
        UNION
        {
            ?individual rdf:type ns:Animal.
            ?individual ?properties ?value
        }
    } #ANIMALS
  }
  ''',
  initNs = { "vcard": vcard, "rdfs":RDFS, "ns":ns}
)


# Visualize the results
for r in g.query(Query3):
  print(r.individual, r.properties, r.value)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO

Query4= prepareQuery('''
  SELECT ?individual WHERE {
  {
    ?individual foaf:knows ?rockyURI.
    ?rockyURI vcard:FN ?rockyFN.

    FILTER(CONTAINS(str(?rockyFN), "Rocky"))
    {
      ?individual rdf:type ?subClass.
      ?subClass rdfs:subClassOf ns:Person.
    }
    UNION
    {
      ?individual rdf:type ns:Person.
    }
  }
}
  ''',
  initNs = { "vcard": vcard.replace("#","/"), "rdfs":RDFS, "ns":ns, "foaf":FOAF}
)


# Visualize the results
for r in g.query(Query4):
  print(r.individual)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
Query5= prepareQuery('''
  SELECT DISTINCT ?entities (COUNT(?other) as ?knownEntities) WHERE
  {

    ?entities foaf:knows ?other.
    FILTER(?entities != ?other).
  } GROUP BY ?entities
    HAVING (COUNT(?other) = 2 || COUNT(?other)>2)
  ''',
  initNs = {"foaf":FOAF}
)


# Visualize the results

for r in g.query(Query5):
  print(r.entities, r.knownEntities)