# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ujMF6_YdBqkGR-in-31DxiGWYCja3npp

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery
ns = Namespace("http://somewhere#")

q1 = prepareQuery('''
    SELECT ?subClass
    WHERE {
        ?subClass rdfs:subClassOf ns:LivingThing.
    }
''',
initNs={"rdfs": RDFS, "ns": ns}
)

# Visualize the results
for r in g.query(q1):
  print(r.subClass)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

q2 = prepareQuery('''
    SELECT ?person
    WHERE {
        ?person ?Algo ns:Person.
    }
''',
initNs={"rdfs": RDFS, "ns": ns}
)

# Visualize the results
for r in g.query(q2):
  print(r.person)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

q3 = prepareQuery('''
    SELECT ?person
    WHERE {
        ?person ?Algo ?tipo.
         FILTER ((?tipo = ns:Person || ?tipo = ns:Animal) && (?Algo != rdfs:SubClassOf))
    }
''',
initNs={"rdfs": RDFS, "ns": ns}
)

# Visualize the results
for r in g.query(q3):
  print(r.person)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

from rdflib import FOAF
from rdflib import XSD
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

q4 = prepareQuery('''
    SELECT ?person
    WHERE {
        ?person foaf:knows ?RockySmith.
        ?RockySmith vcard:FN ?RockySmithFullName.
    }
''',
initNs={"foaf": FOAF,"vcard": VCARD, "xsd":XSD}
)

# Visualize the results
for r in g.query(q4,initBindings = {'?RockySmithFullName' : Literal('Rocky Smith', datatype=XSD.string)}):
  print(r.person)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

q5 = prepareQuery('''
    SELECT ?person
    WHERE {
        ?person foaf:knows ?someone .
        ?person foaf:knows ?someone2 .
        FILTER (?someone != ?someone2)
    }
    GROUP BY ?person
''',
initNs={"foaf": FOAF}
)

# Visualize the results
for r in g.query(q5):
  print(r.person)