# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olSKp6-ZQ93SUu_xnWl29qsX6a81zj-f

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

for s, p, o in g1:
  print(s,p,o)

for s, p, o in g2:
  print(s,p,o)

from rdflib import Graph, Namespace, RDF
from rdflib.namespace import OWL
from rdflib import URIRef


uri1 = "http://data.four.org/#0005"
uri2 = "http://data.four.org/#0003"
uri3 = "http://data.four.org/#0001"

# Convierte la URI en un término URIRef
ns1 = URIRef(uri1)
ns2 = URIRef(uri2)
ns3 = URIRef(uri3)

ns = Namespace("http://somewhere#")

g3.add((ns.JohnDoe, OWL.sameAs, ns1))
g3.add((ns.HarryPotter, OWL.sameAs, ns2))
g3.add((ns.SaraJones, OWL.sameAs, ns3))


for s, p, o in g3:
  print(s,p,o)