# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J19bCo_fF8-Qa61056kkFa6zcZw5VUSn

**Task 07: Querying RDF(s)**
"""


!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
from rdflib.plugins.sparql import prepareQuery
ns = NameSpace("http://somewhere#")

subclases[]
def list_subclasses(x):
  for s, p, o in g.triples((None, RDFS.subClassOf, x)):
    subclasses.append(s)
    list_subclasses(s)
    print(s, p, o)

q1 = prepareQuery('''
SELECT ?subclass
WHERE{
  ?subclass rdfs:subClassOf ns:LivingThing.
}
'''
, initNs ={"rdfs":RDFS, "ns": ns}
)
# Visualize the results

for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
for s, p, o in g.triples((None, RDF.type, ns.Person))
print(s)

for s in g.triples((None, RDFS.subClassOf, ns.Person)):
  for y in g.triples((None, RDF.type, s[0])):
    print(y[0])

q2 = prepareQuery('''
    SELECT ?Person
    WHERE {
      {?Person rdf:type ns:Person. } UNION {
        ?x rdfs:subClassOf ns:Person.
        ?Person rdf:type ?x
      }
    }''',
    initNs = {"ns": ns}


)
# Visualize the results
for r in g.query(q2)
print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
for s,p,o in g.triples((None, RDF.type, ns.Person)):
    for x,y,z in g.triples((s, None, None)):
        print(x, y)

for s,p,o in g.triples((None, RDF.type, ns.Animal)):
    for x,y,z in g.triples((s, None, None)):
        print(x, y)

q3 = prepareQuery('''
  SELECT ?individual ?property ?value
  WHERE {
    ?individual rdfs:subClassOf ?class ;
            ?property ?value .
    FILTER (?class = ns:Person || ?class = ns.Animal)
  }
  ''', initNs={"rdfs": RDFS, "ns": ns}

)
# Visualize the results
for row in g.query(q3):
    print(row.individual, row.property, row.value)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
# Visualize the results
for s, p, o in g.triples((None, ns.knows, ns.Rocky)):
    name = next(g.objects(s, FOAF.name), None)
    print(name)

q4 = prepareQuery('''
  SELECT ?s WHERE { 
    ?s FOAF:knows ns:RockySmith . 
  }
  ''',
  initNs = {"FOAF":FOAF, "ns": ns}
)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
# Visualize the results
count = {}

for s, p, o in g.triples((None, ns.knows, None)):
    if s in count:
        count[s] += 1
    else:
        count[s] = 1


for entity, countF in count.items():
    if countF >= 2:
        print(entity)

q5 = prepareQuery(
    """
    SELECT ?person
    WHERE {
        ?person foaf:knows ?p1 .
        ?person foaf:knows ?p2 .
        FILTER (?p1 != ?p2)
    }
    GROUP BY ?person
    HAVING (COUNT(?p1) >= 2)
    """,
    initNs={"foaf": FOAF}
)