# Generated by Django 3.2.20 on 2023-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ontology_Web_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontology',
            name='content',
        ),
        migrations.AddField(
            model_name='ontology',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ontologies/'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
