# -*- coding: utf-8 -*-
"""queries.sparql.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EUq72OfKxL9P8C3ZXjy8izB73eVCjByH
"""

from rdflib import Graph, Namespace, Literal
g = Graph()

actividades_file = "ActivitiesRDF.ttl"
g.parse(actividades_file, format="turtle")
parques_file = "ParksRDF.ttl"
g.parse(parques_file, format="turtle")

ns1 = Namespace("http://vidaactivamadrid.es/info/ontology/property#")
xsd = Namespace("http://www.w3.org/2001/XMLSchema#")

from rdflib.plugins.sparql import prepareQuery

# All activities with a start date in October 2023

q1 = prepareQuery('''
  SELECT ?activity ?name ?startDate
  WHERE {
    ?activity a <http://vidaactivamadrid.es/info/ontology/class#Activity> .
    ?activity ns1:name ?name .
    ?activity ns1:startDate ?startDate .
    FILTER(REGEX(STR(?startDate), "^2023-10", "i"))
}
  ''',
  initNs = { "ns1": ns1}
)

for r in g.query(q1):
  print(r.activity,r.name,r.startDate)

# All parks in BUENAVISTA

q2 = prepareQuery('''
SELECT ?id_park ?name
WHERE {
  ?id_park a <http://vidaactivamadrid.es/info/ontology/class#Park> .
  ?id_park ns1:isInNeighborhood <http://vidaactivamadrid.es/info/resource/Neighborhood/BUENAVISTA> .
  ?id_park ns1:name ?name
}
  ''',
  initNs = { "ns1": ns1}
)

for r in g.query(q2):
  print(r.id_park,r.name)

# Number of activities without discription

q3 = prepareQuery('''
SELECT ?activity (COUNT(?activity) as ?count)
WHERE {
  ?activity a <http://vidaactivamadrid.es/info/ontology/class#Activity>.
  ?activity ns1:description "Sin descripción".
}
''', initNs = { "ns1": ns1})

for r in g.query(q3):
  print("Sin descripción:", r["count"])

# All facilities with accessibility = 1

q4 = prepareQuery('''
SELECT distinct ?name
WHERE {
  ?facility a <http://vidaactivamadrid.es/info/ontology/class#Facility> .
  ?facility ns1:name ?name.
  ?facility ns1:accessibility "1"

}
  ''',
  initNs = { "ns1": ns1}
)

for r in g.query(q4):
  print(r.name)

# All districts starting with C

q5 = prepareQuery('''
  SELECT ?district ?name
  WHERE {
    ?district a <http://vidaactivamadrid.es/info/ontology/class#District> .
    ?district ns1:name ?name .
    FILTER(REGEX(STR(?name), "^C", "i"))
}
  ''',
  initNs = { "ns1": ns1}
)

for r in g.query(q5):
  print(r.district,r.name)