# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqEh6mQPKmqXubW05SGhvlsjMUvI4csh

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""
print("TASK 6.1")
ns = Namespace("http://somewhere#")
g.add((ns.University, RDF.type, RDFS.Class))
# Visualize the results
print("Printeamos las clases que se encuentran en el grafo, entre ellas, la de universidad:")
for s, p, o in g.triples((None,None,RDFS.Class)):
  print(s,p,o)
print("------------------------------------------------------------------------------------------------------------------------------------------")
"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""
print("TASK 6.2")
ns = Namespace("http://somewhere#")
rdfs = Namespace("https://www.w3.org/TR/rdf-schema/#")
g.add((ns.Researcher, rdfs.subClassOf, ns.Person))
# Visualize the results
print("Printeamos todas las tripletas relacionadas con Researcher")
for s, p, o in g.triples((ns.Researcher,None,None)):
  print(s,p,o)
print("------------------------------------------------------------------------------------------------------------------------------------------")
"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""
print("TASK 6,3")
ns = Namespace("http://somewhere#")
rdfs = Namespace("https://www.w3.org/TR/rdf-schema/#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.JaneSmith,vcard.FN,Literal("Jane Smith")))
g.add((ns.JaneSmith, RDF.type, ns.Researcher))
# Visualize the results
print("Printeamos los triples relacionados con Jane Smith, entre ellos el que indica que es Researcher")
for s, p, o in g.triples((ns.JaneSmith,None,None)):
  print(s,p,o)
print("------------------------------------------------------------------------------------------------------------------------------------------")
"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""
print("TASK 6.4")
ns = Namespace("http://somewhere#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.JaneSmith,vcard.FN,Literal("Jane Smith")))
g.add((ns.JaneSmith,vcard.Given,Literal("Jane")))
g.add((ns.JaneSmith,vcard.Family,Literal("Smith")))
# Visualize the results
print("Printeamos los triples relacionados con Jane Smith")
for s,p,o in g.triples((ns.JaneSmith, None, None)):
  print(s,p,o)
print("------------------------------------------------------------------------------------------------------------------------------------------")
"""**TASK 6.5: Add UPM as the university where John Smith works**"""
print("Task 6.5")
ns = Namespace("http://somewhere#")
rdfs = Namespace("https://www.w3.org/TR/rdf-schema/#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.UPM,RDF.type,ns.University))
g.add((ns.JaneSmith,ns.WorksAt,ns.UPM))
# Visualize the results
print("Printeamos los triples que tengan que ver con Jane Smith")
for s,p,o in g.triples((ns.JaneSmith, None, None)):
  print(s,p,o)
print("------------------------------------------------------------------------------------------------------------------------------------------")
