# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_fVvOEgNMmxWhMhKmYw8PicX0bmoFg2

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
# Visualize the results

ns = Namespace("http://somewhere#")
g.add((ns.University, RDF.type, RDFS.Class))

for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
# Visualize the results

g.add((ns.Researcher, RDF.type, ns.Person))

for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

# TO DO
# Visualize the results

g.add((ns.janeSmith, RDF.type, ns.Researcher))

for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmith the email address, fullName, given and family names**"""

# TO DO
# Visualize the results

janeSmith = ns.JaneSmith
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

g.add((janeSmith, vcard.EMAIL, Literal("jane.smith@example.com")))

g.add((janeSmith, vcard.FN, Literal("Jane Smith")))

g.add((janeSmith, vcard.Given, Literal("Jane")))

g.add((janeSmith, vcard.Family, Literal("Smith")))

for s, p, o in g:
    print(s, p, o)

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

# TO DO
# Visualize the results

upm = ns.UPM
johnSmith = ns.JohnSmith

worksAt = ns.worksAt

g.add((upm, RDF.type, ns.University))
g.add((johnSmith, worksAt, upm))

g.add((upm, RDFS.label, Literal("Universidad Politécnica de Madrid")))

for s, p, o in g:
    print(s, p, o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary**"""

# TO DO
# Visualize the results

FOAF = Namespace("http://xmlns.com/foaf/0.1/")

g.add((johnSmith, FOAF.knows, janeSmith))

for s, p, o in g:
    print(s, p, o)